# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/migrating-from-legacy/

filter_secrets: false
language: node_js

node_js:
  - 10
  - 8
  - 6

os:
  - linux
  - osx
  - windows

matrix:
  include:
    - name: Browser tests (Linux)
      os: linux
      node_js: 10
      env: KARMA=true
      addons:
        firefox: latest
        chrome: stable

    - name: Browser tests (OSX)
      os: osx
      node_js: 10
      env: KARMA=true
      addons:
        firefox: latest
        chrome: stable

    - name: Browser tests (Windows)
      os: linux
      node_js: 10
      env:
        - KARMA=true
        - SAUCE=true

script:
  - npm run lint
  - npm run coverage
  - npm run test:typescript

after_success:
  # concatenate all code-coverage data into a single file
  - ls -R1 coverage/*/lcov.info
  - cat coverage/*/lcov.info > ./coverage/lcov.info

  # send code-coverage data to Coveralls
  - cat ./coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
